[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_VEDIC_API_URL = "https://vedicvn-api.onrender.com/api/chart"
  VITE_GEOAPIFY_API_KEY = "522a159a787444c0bf969ad2a48c63ca"
  VITE_GMAIL_SENDER_EMAIL = "Votiveacademy@gmail.com"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API proxying (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://vedicvn-api.onrender.com/api/:splat"
  status = 200
  force = true

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true 