
[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"     # Hoặc lệnh phù hợp với dự án của bạn
  framework = "#custom"       # Bỏ qua tự động phát hiện framework
  targetPort = 3000           # Cổng mà server backend của bạn lắng nghe
  port = 8888                 # Cổng mà Netlify Dev sẽ sử dụng
  
[build.environment]
  NODE_VERSION = "20.19.2"

