export interface Pada {
    number: number;
    startDegree: number;
    endDegree: number;
    rasi: string;
  }
  
  export interface Nakshatra {
    number: number;
    sanskritName: string;
    vietnameseName: string;
    ruler: string;
    symbol: string;
    startDegree: number;
    endDegree: number;
    deity: string;
    quality: 'Movable' | 'Fixed' | 'Dual';
    gender: 'Male' | 'Female';
    element: 'Fire' | 'Earth' | 'Air' | 'Water';
    padas: Pada[];
  }
  
  export const nakshatras: Nakshatra[] = [
    {
      number: 1,
      sanskritName: 'Ashwini',
      vietnameseName: 'Lâu',
      ruler: 'Ketu',
      symbol: 'Đầu ngựa',
      startDegree: 0,
      endDegree: 13.2,
      deity: 'Ashwini Kumaras',
      quality: 'Movable',
      gender: 'Male',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 0, endDegree: 3.2, rasi: 'Mesha' },
        { number: 2, startDegree: 3.2, endDegree: 6.4, rasi: 'Mesha' },
        { number: 3, startDegree: 6.4, endDegree: 10.0, rasi: 'Mesha' },
        { number: 4, startDegree: 10.0, endDegree: 13.2, rasi: 'Mesha' },
      ],
    },
    {
      number: 2,
      sanskritName: 'Bharani',
      vietnameseName: 'Vị',
      ruler: 'Venus',
      symbol: 'Tử cung',
      startDegree: 13.2,
      endDegree: 26.4,
      deity: 'Yama',
      quality: 'Fixed',
      gender: 'Female',
      element: 'Earth',
      padas: [
        { number: 1, startDegree: 13.2, endDegree: 16.4, rasi: 'Mesha' },
        { number: 2, startDegree: 16.4, endDegree: 20.0, rasi: 'Mesha' },
        { number: 3, startDegree: 20.0, endDegree: 23.2, rasi: 'Mesha' },
        { number: 4, startDegree: 23.2, endDegree: 26.4, rasi: 'Mesha' },
      ],
    },
    {
      number: 3,
      sanskritName: 'Krittika',
      vietnameseName: 'Mão',
      ruler: 'Sun',
      symbol: 'Dao cắt',
      startDegree: 26.4,
      endDegree: 40.0,
      deity: 'Agni',
      quality: 'Dual',
      gender: 'Female',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 26.4, endDegree: 30.0, rasi: 'Mesha' },
        { number: 2, startDegree: 30.0, endDegree: 33.2, rasi: 'Vrishabha' },
        { number: 3, startDegree: 33.2, endDegree: 36.4, rasi: 'Vrishabha' },
        { number: 4, startDegree: 36.4, endDegree: 40.0, rasi: 'Vrishabha' },
      ],
    },
    {
      number: 4,
      sanskritName: 'Rohini',
      vietnameseName: 'Tất',
      ruler: 'Moon',
      symbol: 'Xe ngựa',
      startDegree: 40.0,
      endDegree: 53.2,
      deity: 'Brahma',
      quality: 'Fixed',
      gender: 'Female',
      element: 'Earth',
      padas: [
        { number: 1, startDegree: 40.0, endDegree: 43.2, rasi: 'Vrishabha' },
        { number: 2, startDegree: 43.2, endDegree: 46.4, rasi: 'Vrishabha' },
        { number: 3, startDegree: 46.4, endDegree: 50.0, rasi: 'Vrishabha' },
        { number: 4, startDegree: 50.0, endDegree: 53.2, rasi: 'Vrishabha' },
      ],
    },
    {
      number: 5,
      sanskritName: 'Mrigashira',
      vietnameseName: 'Sâm',
      ruler: 'Mars',
      symbol: 'Đầu hươu',
      startDegree: 53.2,
      endDegree: 66.4,
      deity: 'Soma',
      quality: 'Movable',
      gender: 'Male',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 53.2, endDegree: 56.4, rasi: 'Vrishabha' },
        { number: 2, startDegree: 56.4, endDegree: 60.0, rasi: 'Vrishabha' },
        { number: 3, startDegree: 60.0, endDegree: 63.2, rasi: 'Mithuna' },
        { number: 4, startDegree: 63.2, endDegree: 66.4, rasi: 'Mithuna' },
      ],
    },
    {
      number: 6,
      sanskritName: 'Ardra',
      vietnameseName: 'Tỉnh',
      ruler: 'Rahu',
      symbol: 'Giọt nước mắt',
      startDegree: 66.4,
      endDegree: 80.0,
      deity: 'Rudra',
      quality: 'Movable',
      gender: 'Female',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 66.4, endDegree: 70.0, rasi: 'Mithuna' },
        { number: 2, startDegree: 70.0, endDegree: 73.2, rasi: 'Mithuna' },
        { number: 3, startDegree: 73.2, endDegree: 76.4, rasi: 'Mithuna' },
        { number: 4, startDegree: 76.4, endDegree: 80.0, rasi: 'Mithuna' },
      ],
    },
    {
      number: 7,
      sanskritName: 'Punarvasu',
      vietnameseName: 'Quỷ',
      ruler: 'Jupiter',
      symbol: 'Ống tên',
      startDegree: 80.0,
      endDegree: 93.2,
      deity: 'Aditi',
      quality: 'Dual',
      gender: 'Female',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 80.0, endDegree: 83.2, rasi: 'Mithuna' },
        { number: 2, startDegree: 83.2, endDegree: 86.4, rasi: 'Mithuna' },
        { number: 3, startDegree: 86.4, endDegree: 90.0, rasi: 'Mithuna' },
        { number: 4, startDegree: 90.0, endDegree: 93.2, rasi: 'Karkata' },
      ],
    },
    {
      number: 8,
      sanskritName: 'Pushya',
      vietnameseName: 'Liễu',
      ruler: 'Saturn',
      symbol: 'Vòng hoa',
      startDegree: 93.2,
      endDegree: 106.4,
      deity: 'Brihaspati',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 93.2, endDegree: 96.4, rasi: 'Karkata' },
        { number: 2, startDegree: 96.4, endDegree: 100.0, rasi: 'Karkata' },
        { number: 3, startDegree: 100.0, endDegree: 103.2, rasi: 'Karkata' },
        { number: 4, startDegree: 103.2, endDegree: 106.4, rasi: 'Karkata' },
      ],
    },
    {
      number: 9,
      sanskritName: 'Ashlesha',
      vietnameseName: 'Tinh',
      ruler: 'Mercury',
      symbol: 'Con rắn',
      startDegree: 106.4,
      endDegree: 120.0,
      deity: 'Naga',
      quality: 'Movable',
      gender: 'Female',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 106.4, endDegree: 110.0, rasi: 'Karkata' },
        { number: 2, startDegree: 110.0, endDegree: 113.2, rasi: 'Karkata' },
        { number: 3, startDegree: 113.2, endDegree: 116.4, rasi: 'Karkata' },
        { number: 4, startDegree: 116.4, endDegree: 120.0, rasi: 'Karkata' },
      ],
    },
    {
      number: 10,
      sanskritName: 'Magha',
      vietnameseName: 'Trương',
      ruler: 'Ketu',
      symbol: 'Ngai vàng',
      startDegree: 120.0,
      endDegree: 133.2,
      deity: 'Pitris',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 120.0, endDegree: 123.2, rasi: 'Simha' },
        { number: 2, startDegree: 123.2, endDegree: 126.4, rasi: 'Simha' },
        { number: 3, startDegree: 126.4, endDegree: 130.0, rasi: 'Simha' },
        { number: 4, startDegree: 130.0, endDegree: 133.2, rasi: 'Simha' },
      ],
    },
    {
      number: 11,
      sanskritName: 'Purva Phalguni',
      vietnameseName: 'Dực',
      ruler: 'Venus',
      symbol: 'Chiếc giường',
      startDegree: 133.2,
      endDegree: 146.4,
      deity: 'Bhaga',
      quality: 'Movable',
      gender: 'Female',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 133.2, endDegree: 136.4, rasi: 'Simha' },
        { number: 2, startDegree: 136.4, endDegree: 140.0, rasi: 'Simha' },
        { number: 3, startDegree: 140.0, endDegree: 143.2, rasi: 'Simha' },
        { number: 4, startDegree: 143.2, endDegree: 146.4, rasi: 'Simha' },
      ],
    },
    {
      number: 12,
      sanskritName: 'Uttara Phalguni',
      vietnameseName: 'Chẩn',
      ruler: 'Sun',
      symbol: 'Chân sau của giường',
      startDegree: 146.4,
      endDegree: 160.0,
      deity: 'Aryaman',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 146.4, endDegree: 150.0, rasi: 'Simha' },
        { number: 2, startDegree: 150.0, endDegree: 153.2, rasi: 'Kanya' },
        { number: 3, startDegree: 153.2, endDegree: 156.4, rasi: 'Kanya' },
        { number: 4, startDegree: 156.4, endDegree: 160.0, rasi: 'Kanya' },
      ],
    },
    {
      number: 13,
      sanskritName: 'Hasta',
      vietnameseName: 'Giác',
      ruler: 'Moon',
      symbol: 'Bàn tay',
      startDegree: 160.0,
      endDegree: 173.2,
      deity: 'Savitar',
      quality: 'Dual',
      gender: 'Male',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 160.0, endDegree: 163.2, rasi: 'Kanya' },
        { number: 2, startDegree: 163.2, endDegree: 166.4, rasi: 'Kanya' },
        { number: 3, startDegree: 166.4, endDegree: 170.0, rasi: 'Kanya' },
        { number: 4, startDegree: 170.0, endDegree: 173.2, rasi: 'Kanya' },
      ],
    },
    {
      number: 14,
      sanskritName: 'Chitra',
      vietnameseName: 'Cang',
      ruler: 'Mars',
      symbol: 'Viên ngọc',
      startDegree: 173.2,
      endDegree: 186.4,
      deity: 'Vishvakarma',
      quality: 'Movable',
      gender: 'Female',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 173.2, endDegree: 176.4, rasi: 'Kanya' },
        { number: 2, startDegree: 176.4, endDegree: 180.0, rasi: 'Kanya' },
        { number: 3, startDegree: 180.0, endDegree: 183.2, rasi: 'Tula' },
        { number: 4, startDegree: 183.2, endDegree: 186.4, rasi: 'Tula' },
      ],
    },
    {
      number: 15,
      sanskritName: 'Swati',
      vietnameseName: 'Đê',
      ruler: 'Rahu',
      symbol: 'Cây sậy',
      startDegree: 186.4,
      endDegree: 200.0,
      deity: 'Vayu',
      quality: 'Movable',
      gender: 'Male',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 186.4, endDegree: 190.0, rasi: 'Tula' },
        { number: 2, startDegree: 190.0, endDegree: 193.2, rasi: 'Tula' },
        { number: 3, startDegree: 193.2, endDegree: 196.4, rasi: 'Tula' },
        { number: 4, startDegree: 196.4, endDegree: 200.0, rasi: 'Tula' },
      ],
    },
    {
      number: 16,
      sanskritName: 'Vishakha',
      vietnameseName: 'Phòng',
      ruler: 'Jupiter',
      symbol: 'Cổng khải hoàn',
      startDegree: 200.0,
      endDegree: 213.2,
      deity: 'Indra-Agni',
      quality: 'Fixed',
      gender: 'Female',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 200.0, endDegree: 203.2, rasi: 'Tula' },
        { number: 2, startDegree: 203.2, endDegree: 206.4, rasi: 'Tula' },
        { number: 3, startDegree: 206.4, endDegree: 210.0, rasi: 'Tula' },
        { number: 4, startDegree: 210.0, endDegree: 213.2, rasi: 'Vrischika' },
      ],
    },
    {
      number: 17,
      sanskritName: 'Anuradha',
      vietnameseName: 'Tâm',
      ruler: 'Saturn',
      symbol: 'Cây gậy',
      startDegree: 213.2,
      endDegree: 226.4,
      deity: 'Mitra',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 213.2, endDegree: 216.4, rasi: 'Vrischika' },
        { number: 2, startDegree: 216.4, endDegree: 220.0, rasi: 'Vrischika' },
        { number: 3, startDegree: 220.0, endDegree: 223.2, rasi: 'Vrischika' },
        { number: 4, startDegree: 223.2, endDegree: 226.4, rasi: 'Vrischika' },
      ],
    },
    {
      number: 18,
      sanskritName: 'Jyeshtha',
      vietnameseName: 'Vĩ',
      ruler: 'Mercury',
      symbol: 'Vòng trang sức',
      startDegree: 226.4,
      endDegree: 240.0,
      deity: 'Indra',
      quality: 'Fixed',
      gender: 'Female',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 226.4, endDegree: 230.0, rasi: 'Vrischika' },
        { number: 2, startDegree: 230.0, endDegree: 233.2, rasi: 'Vrischika' },
        { number: 3, startDegree: 233.2, endDegree: 236.4, rasi: 'Vrischika' },
        { number: 4, startDegree: 236.4, endDegree: 240.0, rasi: 'Vrischika' },
      ],
    },
    {
      number: 19,
      sanskritName: 'Mula',
      vietnameseName: 'Cơ',
      ruler: 'Ketu',
      symbol: 'Đuôi sư tử',
      startDegree: 240.0,
      endDegree: 253.2,
      deity: 'Nirriti',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 240.0, endDegree: 243.2, rasi: 'Dhanus' },
        { number: 2, startDegree: 243.2, endDegree: 246.4, rasi: 'Dhanus' },
        { number: 3, startDegree: 246.4, endDegree: 250.0, rasi: 'Dhanus' },
        { number: 4, startDegree: 250.0, endDegree: 253.2, rasi: 'Dhanus' },
      ],
    },
    {
      number: 20,
      sanskritName: 'Purva Ashadha',
      vietnameseName: 'Đẩu',
      ruler: 'Venus',
      symbol: 'Quạt',
      startDegree: 253.2,
      endDegree: 266.4,
      deity: 'Apas',
      quality: 'Movable',
      gender: 'Female',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 253.2, endDegree: 256.4, rasi: 'Dhanus' },
        { number: 2, startDegree: 256.4, endDegree: 260.0, rasi: 'Dhanus' },
        { number: 3, startDegree: 260.0, endDegree: 263.2, rasi: 'Dhanus' },
        { number: 4, startDegree: 263.2, endDegree: 266.4, rasi: 'Dhanus' },
      ],
    },
    {
      number: 21,
      sanskritName: 'Uttara Ashadha',
      vietnameseName: 'Ngưu',
      ruler: 'Sun',
      symbol: 'Ngà voi',
      startDegree: 266.4,
      endDegree: 280.0,
      deity: 'Vishvedevas',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Earth',
      padas: [
        { number: 1, startDegree: 266.4, endDegree: 270.0, rasi: 'Dhanus' },
        { number: 2, startDegree: 270.0, endDegree: 273.2, rasi: 'Makara' },
        { number: 3, startDegree: 273.2, endDegree: 276.4, rasi: 'Makara' },
        { number: 4, startDegree: 276.4, endDegree: 280.0, rasi: 'Makara' },
      ],
    },
    {
      number: 22,
      sanskritName: 'Shravana',
      vietnameseName: 'Nữ',
      ruler: 'Moon',
      symbol: 'Ba dấu chân',
      startDegree: 280.0,
      endDegree: 293.2,
      deity: 'Vishnu',
      quality: 'Movable',
      gender: 'Female',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 280.0, endDegree: 283.2, rasi: 'Makara' },
        { number: 2, startDegree: 283.2, endDegree: 286.4, rasi: 'Makara' },
        { number: 3, startDegree: 286.4, endDegree: 290.0, rasi: 'Makara' },
        { number: 4, startDegree: 290.0, endDegree: 293.2, rasi: 'Makara' },
      ],
    },
    {
      number: 23,
      sanskritName: 'Dhanishta',
      vietnameseName: 'Hư',
      ruler: 'Mars',
      symbol: 'Trống',
      startDegree: 293.2,
      endDegree: 306.4,
      deity: 'Vasus',
      quality: 'Dual',
      gender: 'Male',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 293.2, endDegree: 296.4, rasi: 'Makara' },
        { number: 2, startDegree: 296.4, endDegree: 300.0, rasi: 'Makara' },
        { number: 3, startDegree: 300.0, endDegree: 303.2, rasi: 'Kumbha' },
        { number: 4, startDegree: 303.2, endDegree: 306.4, rasi: 'Kumbha' },
      ],
    },
    {
      number: 24,
      sanskritName: 'Satabhisha',
      vietnameseName: 'Nguy',
      ruler: 'Rahu',
      symbol: 'Vòng tròn',
      startDegree: 306.4,
      endDegree: 320.0,
      deity: 'Varuna',
      quality: 'Fixed',
      gender: 'Female',
      element: 'Air',
      padas: [
        { number: 1, startDegree: 306.4, endDegree: 310.0, rasi: 'Kumbha' },
        { number: 2, startDegree: 310.0, endDegree: 313.2, rasi: 'Kumbha' },
        { number: 3, startDegree: 313.2, endDegree: 316.4, rasi: 'Kumbha' },
        { number: 4, startDegree: 316.4, endDegree: 320.0, rasi: 'Kumbha' },
      ],
    },
    {
      number: 25,
      sanskritName: 'Purva Bhadrapada',
      vietnameseName: 'Thất',
      ruler: 'Jupiter',
      symbol: 'Thanh gươm',
      startDegree: 320.0,
      endDegree: 333.2,
      deity: 'Aja Ekapada',
      quality: 'Fixed',
      gender: 'Male',
      element: 'Fire',
      padas: [
        { number: 1, startDegree: 320.0, endDegree: 323.2, rasi: 'Kumbha' },
        { number: 2, startDegree: 323.2, endDegree: 326.4, rasi: 'Kumbha' },
        { number: 3, startDegree: 326.4, endDegree: 330.0, rasi: 'Kumbha' },
        { number: 4, startDegree: 330.0, endDegree: 333.2, rasi: 'Mina' },
      ],
    },
    {
      number: 26,
      sanskritName: 'Uttara Bhadrapada',
      vietnameseName: 'Bích',
      ruler: 'Saturn',
      symbol: 'Cặp song sinh',
      startDegree: 333.2,
      endDegree: 346.4,
      deity: 'Ahir Budhnya',
      quality: 'Movable',
      gender: 'Female',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 333.2, endDegree: 336.4, rasi: 'Mina' },
        { number: 2, startDegree: 336.4, endDegree: 340.0, rasi: 'Mina' },
        { number: 3, startDegree: 340.0, endDegree: 343.2, rasi: 'Mina' },
        { number: 4, startDegree: 343.2, endDegree: 346.4, rasi: 'Mina' },
      ],
    },
    {
      number: 27,
      sanskritName: 'Revati',
      vietnameseName: 'Khuê',
      ruler: 'Mercury',
      symbol: 'Cá',
      startDegree: 346.4,
      endDegree: 360.0,
      deity: 'Pushan',
      quality: 'Dual',
      gender: 'Male',
      element: 'Water',
      padas: [
        { number: 1, startDegree: 346.4, endDegree: 350.0, rasi: 'Mina' },
        { number: 2, startDegree: 350.0, endDegree: 353.2, rasi: 'Mina' },
        { number: 3, startDegree: 353.2, endDegree: 356.4, rasi: 'Mina' },
        { number: 4, startDegree: 356.4, endDegree: 360.0, rasi: 'Mina' },
      ],
    },
  ];