/**
 * Page 2: 16 D-Varga Charts
 * Grid layout 4x4 using actual vargas data from chart
 */

import React from 'react';
import { View, Text, Image, StyleSheet } from '@react-pdf/renderer';
import { page2Styles, colors, fontSizes, spacing } from '../styles';
import { PdfReportData } from '../types';

// Get vargas from chartData, map to expected format
const getVargasData = (data: PdfReportData) => {
  const vargasMap = data.chartData.vargas || [];
  return vargasMap.map(v => ({
    id: v.id,
    name: getVargaName(v.id),
    key: v.id,
    planets: v.planets,
    ascendantSign: v.ascendantSign,
  }));
};

// Get Vietnamese name for varga
function getVargaName(id: string): string {
  const names: Record<string, string> = {
    'D1': 'Rasi',
    'D2': 'Hora',
    'D3': 'Drekkana',
    'D4': 'Chaturamsa',
    'D7': 'Saptamsa',
    'D9': 'Navamsa',
    'D10': 'Dasamsa',
    'D12': 'Dwadamsa',
    'D16': 'Shodasamsa',
    'D20': 'Vimsamsa',
    'D24': 'Siddhamsa',
    'D27': 'Nakshatramsa',
    'D30': 'Trimsamsa',
    'D40': 'Khavedamsa',
    'D45': 'Akshvedamsa',
    'D60': 'Shashtiamsa',
  };
  return names[id] || id;
}

interface Page2Props {
  data: PdfReportData;
}

// Single Varga Chart Cell - no borders for maximum space
const VargaCell: React.FC<{
  varga: { id: string; name: string; key: string };
  image?: string;
}> = ({ varga, image }) => (
  <View style={page2Styles.vargaCell}>
    <Text style={page2Styles.vargaTitle}>
      {varga.id} - {varga.name}
    </Text>
    {image ? (
      <Image src={image} style={page2Styles.vargaImage} />
    ) : (
      <View style={page2Styles.vargaPlaceholder}>
        <Text style={page2Styles.vargaPlaceholderText}>N/A</Text>
      </View>
    )}
  </View>
);

// Page 2 Header
const Page2Header: React.FC = () => (
  <View style={page2Styles.header}>
    <Text style={page2Styles.headerTitle}>HE THONG 16 D-VARGA (PHAN CUNG)</Text>
    <Text style={page2Styles.headerSubtitle}>Theo he thong Parashara - Divisional Charts</Text>
  </View>
);

export const Page2: React.FC<Page2Props> = ({ data }) => {
  const vargas = getVargasData(data);

  return (
    <View style={page2Styles.container}>
      {/* Header */}
      <Page2Header />

      {/* Vargas Grid 4x4 - use actual data */}
      <View style={page2Styles.vargasGrid}>
        {vargas.map((varga) => (
          <VargaCell
            key={varga.key}
            varga={varga}
            image={data.vargaChartImages?.[varga.key]}
          />
        ))}
      </View>

      {/* Footer */}
      <Text style={page2Styles.footer}>Generated by Votive VedicVN 2026, All rights reserved</Text>
    </View>
  );
};
