/**
 * Page 2: 16 D-Varga Charts
 * Grid layout 4x4 using actual vargas data from chart
 */

import React from 'react';
import { View, Text, Image } from '@react-pdf/renderer';
import { page2Styles, commonStyles, colors, fontSizes, spacing } from '../styles';
import { PdfReportData } from '../types';

// Standard 16 D-Varga list
const VARGAS_LIST = [
  { id: 'D1', name: 'Rasi' },
  { id: 'D2', name: 'Hora' },
  { id: 'D3', name: 'Drekkana' },
  { id: 'D4', name: 'Chaturamsa' },
  { id: 'D7', name: 'Saptamsa' },
  { id: 'D9', name: 'Navamsa' },
  { id: 'D10', name: 'Dasamsa' },
  { id: 'D12', name: 'Dwadamsa' },
  { id: 'D16', name: 'Shodasamsa' },
  { id: 'D20', name: 'Vimsamsa' },
  { id: 'D24', name: 'Siddhamsa' },
  { id: 'D27', name: 'Nakshatramsa' },
  { id: 'D30', name: 'Trimsamsa' },
  { id: 'D40', name: 'Khavedamsa' },
  { id: 'D45', name: 'Akshvedamsa' },
  { id: 'D60', name: 'Shashtiamsa' },
];

// Get vargas from chartData
const getVargasData = (data: PdfReportData) => {
  const vargasMap = data.chartData.vargas || [];
  return VARGAS_LIST.map(v => {
    const found = vargasMap.find(va => va.id === v.id);
    return {
      id: v.id,
      name: v.name,
      key: v.id,
      hasData: !!found,
    };
  });
};

interface Page2Props {
  data: PdfReportData;
}

// Single Varga Chart Cell - no borders for maximum space
const VargaCell: React.FC<{
  varga: { id: string; name: string; key: string };
  image?: string;
}> = ({ varga, image }) => (
  <View style={page2Styles.vargaCell}>
    <Text style={page2Styles.vargaTitle}>
      {varga.id}
    </Text>
    {image ? (
      <Image src={image} style={page2Styles.vargaImage} />
    ) : (
      <View style={page2Styles.vargaPlaceholder}>
        <Text style={page2Styles.vargaPlaceholderText}>-</Text>
      </View>
    )}
  </View>
);

// Page 2 Header
const Page2Header: React.FC = () => (
  <View style={page2Styles.header}>
    <Text style={page2Styles.headerTitle}>HE THONG 16 D-VARGA (PHAN CUNG)</Text>
    <Text style={page2Styles.headerSubtitle}>Theo he thong Parashara - Divisional Charts</Text>
  </View>
);

export const Page2: React.FC<Page2Props> = ({ data }) => {
  const vargas = getVargasData(data);

  return (
    <View style={page2Styles.container}>
      {/* Header */}
      <Page2Header />

      {/* Vargas Grid 4x4 */}
      <View style={page2Styles.vargasGrid}>
        {vargas.map((varga) => (
          <VargaCell
            key={varga.key}
            varga={varga}
            image={data.vargaChartImages?.[varga.key]}
          />
        ))}
      </View>

      {/* Footer */}
      <Text style={commonStyles.footer}>Generated by Votive VedicVN 2026, All rights reserved</Text>
    </View>
  );
};
