// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzyyiqzekduduoscdwjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eXlpcXpla2R1ZHVvc2Nkd2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTk0NTEsImV4cCI6MjA1OTU3NTQ1MX0.4RA_PWjKWB0liNQv2FJ14eK_fQ8Nl1uTnQxMk-RWc1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

<<<<<<< HEAD
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
// Add retry functionality for failed requests
export const safeQuery = async (queryFn: () => Promise<any>, context: string) => {
    try {
        const result = await queryFn();
        if (result.error) {
            throw result.error;
        }
        return result;
    } catch (error) {
        return handleSupabaseError(error, context);
    }
};
