
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fccsmfhjcyztrymcsbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjY3NtZmhqY3l6dHJ5bWNzYmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTg0MDQsImV4cCI6MjA1OTQ5NDQwNH0.75abaQDmXbuwSuZ2F4jHpWxDCNVTGKDzKHxjhH80v9Y";

// Create a Supabase client with proper configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false
    }
  }
);
